language: php

matrix:
  fast_finish: true
  include:
  - php: "7.2"
  - php: "7.3"
  - php: "7.4"
  allow_failures:
  - php: nightly

before_script:
  - travis_retry composer self-update
  - composer install

script:
  - php vendor/bin/phpunit -c phpunit.xml
