language: php

php:
  - hhvm
  - nightly

matrix:
  fast_finish: true
  include:
  - php: 7.1
  - php: 7.2
  - php: nightly
  allow_failures:
  - php: hhvm
  - php: nightly

before_script:
  - travis_retry composer self-update
  - composer install

script:
  - php vendor/bin/phpunit -c phpunit.xml
